# frozen_string_literal: true
source 'https://rubygems.org'

ruby '>= 3.4.0'

gem 'sinatra', '~> 4.1'
gem 'puma', '~> 6.4'
gem 'tilt', '~> 2.6'
gem 'erubi', '~> 1.13'
gem 'sequel', '~> 5.0'
gem 'sqlite3', '>= 2.0'
gem 'rack-protection', '~> 4.0'
